Repository NeurodataWithoutBorders/nwbinspector, pull requests merged in 2022-11, with the labels that each got.

#299 [Documentation]: Inspection on in-memory nwbfile
  docs/user_guide/using_the_library.rst
  src/nwbinspector/__init__.py
Labels: topic: docs

#303 [Bug fix]: hotfix configuration importance
  src/nwbinspector/nwbinspector.py
  src/nwbinspector/register_checks.py
  tests/test_inspector.py
Labels: category: bug

#296 Debug lazy dataset class types and timestamps loading
  src/nwbinspector/checks/time_series.py
  src/nwbinspector/utils.py
  tests/test_inspector.py
  tests/true_nwbinspector_default_report.txt
  tests/unit_tests/test_time_series.py
Labels: category: enhancement, priority: high

#305 Add test confirming expected config+threshold behavior
  tests/test_check_configuration.py
Labels: topic: testing

#308 Fix 307
  src/nwbinspector/checks/time_series.py
Labels: category: enhancement

#306 Add downstream DANDI CI
  .github/workflows/dandi-dev.yml
  .github/workflows/dandi-release.yml
  .github/workflows/deploy-tests.yml
  src/nwbinspector/nwbinspector.py
  tests/test_inspector.py
Labels: topic: testing

#311 Include compression in ImageSeries size check
  CHANGELOG.md
  src/nwbinspector/checks/image_series.py
  tests/unit_tests/test_image_series.py
Labels: category: enhancement

#301 Add false positive skip for ImageSeries check on TwoPhotonSeries
  src/nwbinspector/checks/image_series.py
  tests/unit_tests/test_ophys.py
Labels: category: enhancement

#315 fix get_data_shape for unbounded dataset
  CHANGELOG.md
  src/nwbinspector/checks/ecephys.py
  src/nwbinspector/checks/ophys.py
  src/nwbinspector/checks/tables.py
  src/nwbinspector/checks/time_series.py
  src/nwbinspector/utils.py
  tests/unit_tests/test_time_series.py
Labels: category: bug

#316 Dynamic table unique ids
  CHANGELOG.md
  docs/best_practices/tables.rst
  src/nwbinspector/checks/ecephys.py
  src/nwbinspector/checks/tables.py
  src/nwbinspector/utils.py
  tests/unit_tests/test_tables.py
Labels: category: new check
