Repository NeurodataWithoutBorders/nwbinspector, pull requests merged in 2022-02, with the labels that each got.

#49 Make checks iterable
  nwbinspector/nwbinspector.py
  nwbinspector/register_checks.py
  nwbinspector/tools.py
  tests/test_inspector.py
  tests/unit_tests/test_nwbfile_metadata.py
Labels: enhancement

#56 added optional disabling of color from CLI
  nwbinspector/inspector_tools.py
  nwbinspector/nwbinspector.py
Labels: bug

#55 fix save path for log file
  nwbinspector/nwbinspector.py
  tests/test_inspector.py
Labels: bug

#62 Propogate validiation and errors
  nwbinspector/inspector_tools.py
  nwbinspector/nwbinspector.py
  tests/test_inspector.py
Labels: enhancement

#75 [Dev Feature]: auto-publish to PyPI
  .github/workflows/auto-publish.yml
Labels: enhancement

#78 Make report saving optional (only CLI by default)
  nwbinspector/inspector_tools.py
  nwbinspector/nwbinspector.py
  tests/test_inspector.py
  tests/true_nwbinspector_report.txt
Labels: high priority

#82 Proposal for a logo for the NWBInsepctor
  README.md
  logo/logo.pdf
  logo/logo.png
  logo/logo.pptx
Labels: documentation, low priority

#71 Improved templates for issues
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/new_check.yml
Labels: documentation, enhancement
